### PR TITLE
#213: Invoke method consist of extended data type cause access violation

### PR DESCRIPTION
**Pull request by ccy**

### CODE REVIEW

**Comment by carlokok** [comment]
What's the patchprocptr stuff for ? (the rest looks good)

**Comment by ccy** [comment]
patchprocptr?  What is that?  Did I commit anything related to patchprocptr ?

**Comment by carlokok** [comment]
https://github.com/remobjects/pascalscript/pull/214/files#diff-d606fb5e6c50a5f9418c0828d9a7b52aR28

there's code related to patching procptr in your pull request.

**Comment by ccy** [comment]
My mistake. I will close this pull request and create a new one.

**Pull request closed without merging**
