### PR TITLE
1)InvokeCall added - instead of all different calls …

### PR DESCRIPTION
**Pull request by Vizit0r**
...(x86, x64, powerpc etc) for Delphi 2010+.

Tested on Win x86&x64, Android, MacOS32 - no problems observed.

2) Changes for correct MACOS compilation in Delphi

### CODE REVIEW

**Comment by carlokok** [comment]
I think we're almost there. I don't have d6/7d7 handy at the moment, but I recall:


  {$IF DEFINED (MSWINDOWS) OR Defined (UNIX) OR Defined (fpc)}

those don't work in it. They require 2010+ too.

**Comment by Vizit0r** [comment]
It's calling dll, it was declared before for any Delphi version - i'm just checking for preventing run it on *IX systems in Delphi (Delphi have no default conditional define UNIX). Really, this dll calling module should be filled up with different methods for different OS (in Delphi), and maybe i will do this - but that will be at least next year.

**Comment by carlokok** [comment]
My point as that delphi pre-2010 fail to compile the {$IF expressions} all together.

**Comment by Vizit0r** [comment]
will install Delphi 7 and check it today

**Comment by Vizit0r** [comment]
make few changes for correct work on D7.
New pull request done.

**Pull request closed without merging**
